# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BES' do
 
  use_frameworks!

  pod 'Alamofire', '~> 4.7'
  pod "PromiseKit/Foundation", "~> 6.0"
  pod 'RxSwift', '~> 4.3.1'
  pod 'RxCocoa', '~> 4.3.1'
  pod 'SDWebImage', '~> 5.0'
  pod 'DropDown', '2.3.4'
  pod 'MBProgressHUD'

end
