# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BES' do
 
  use_frameworks!

  pod 'Alamofire'
  pod 'ObjectMapper'
  pod 'SDWebImage'
  pod 'DropDown'
  pod 'MBProgressHUD'
  pod 'IQKeyboardManager'
  pod 'SimpleImageViewer'
  pod 'DropDown'

end
